<a href="https://colab.research.google.com/github/435wldms/essa/blob/main/20231117_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 06 아이템 기반 최근접 이웃 협업 필터링 실습

* 아이템 기반 협업 필터링 구현

**데이터 가공 및 변환**

In [1]:
import pandas as pd
import numpy as np

movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

print(movies.shape)
print(ratings.shape)

(9742, 3)
(100836, 4)

-> movies: 영화에 대한 메타정보인 title, genres 가짐, ratings: 사용자별로 영화에 대한 평점을 매긴 것(0.5단위로 평점)

* 아이템 기반의 최근접 이웃 협업 필터링 수행을 위해 로우 레벨 형태의 원본 데이터 세트를 변경해야함 (모든 사용자: 로우, 모든 영화: 컬럼)

In [2]:
# pivot_table() 함수로 변환
ratings = ratings[['userId','movieId','rating']]
ratings_matrix = ratings.pivot_table('rating', index='userId', columns='movieId')
ratings_matrix.head(3)

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

-> 사용자가 평점을 매기지 않은 영화가 많아 nan 값이 많은데 최소 평점이 0.5이므로 0으로 nan 값을 대체

* 가독성을 높이기 위해 칼럼명을 movieId가 아닌 영화명 title로 변경

In [3]:
# title 칼럼을 얻기 위해 movies와 조인
rating_movies = pd.merge(ratings, movies, on='movieId')

# columns='title'로 title 칼럼으로 피벗 수행.
ratings_matrix = rating_movies.pivot_table('rating', index='userId', columns='title')

# NaN 값을 모두 0으로 변환
ratings_matrix = ratings_matrix.fillna(0)
ratings_matrix.head(3)

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

**영화 간 유사도 산출**
* cosine_similarity 이용 -> 영화 간의 유사도가 아닌 행 간의 (사용자) 유사도 구함
* 행 기준이 영화가 되어야 사용 가능

In [4]:
ratings_matrix_T = ratings_matrix.transpose()
ratings_matrix_T.head(3)

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
'Hellboy': The Seeds of Creation (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Round Midnight (1986),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
# 영화의 코사인 유사도
from sklearn.metrics.pairwise import cosine_similarity

item_sim = cosine_similarity(ratings_matrix_T,ratings_matrix_T)

# cosine_similarity()로 반환된 넘파이 행렬을 영화명을 매핑해 DataFrame으로 변환
item_sim_df = pd.DataFrame(data=item_sim, index=ratings_matrix.columns, columns=ratings_matrix.columns)
print(item_sim_df.shape)
item_sim_df.head(3)

(9719, 9719)

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),1.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.141653,0.0,...,0.0,0.342055,0.543305,0.707107,0.0,0.0,0.139431,0.327327,0.0,0.0
'Hellboy': The Seeds of Creation (2004),0.0,1.000000,0.707107,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
'Round Midnight (1986),0.0,0.707107,1.000000,0.0,0.0,0.0,0.176777,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0

* '대부'와 유사도가 높은 상위 6개 영화 추출

In [6]:
item_sim_df['Godfather, The (1972)'].sort_values(ascending=False)[:6]

title
Godfather, The (1972)                        1.000000
Godfather: Part II, The (1974)               0.821773
Goodfellas (1990)                            0.664841
One Flew Over the Cuckoo's Nest (1975)       0.620536
Star Wars: Episode IV - A New Hope (1977)    0.595317
Fargo (1996)                                 0.588614
Name: Godfather, The (1972), dtype: float64

In [7]:
item_sim_df['Inception (2010)'].sort_values(ascending=False)[1:6]

title
Dark Knight, The (2008)          0.727263
Inglourious Basterds (2009)      0.646103
Shutter Island (2010)            0.617736
Dark Knight Rises, The (2012)    0.617504
Fight Club (1999)                0.615417
Name: Inception (2010), dtype: float64

**아이템 기반 최근접 이웃 협업 필터링으로 개인화된 영화 추천**

* 이전 코드는 개인적인 취향을 반영하지 않고 영화 간의 유사도만 반영 -> 개인에게 최적화된 영화 추천 구현
![image.png]()

* 이때, n 값은 아이템의 최근접 이웃 범위 계수를 의미
* 먼저 n의 범위에 제약을 두지 않고 모든 아이템으로 가정하고 예측 평점을 구하는 로직을 작성한 후, top-n 아이템을 기반으로 협업 필터링 수행
* 사용자 별로 최적화된 평점 스코어 예측 함수 생성
 -> 사용자 u의 모든 영화에 대한 실제 평점과 영화 i의 다른 모든 영화와의 코사인 유사도를 벡터 내적 곱한 값을 정규화를 위해 sigma로 나눈 것

In [8]:
def predict_rating(ratings_arr, item_sim_arr):
  ratings_pred = ratings_arr.dot(item_sim_arr)/np.array([np.abs(item_sim_arr).sum(axis=1)])
  return ratings_pred

* predict_rating() 함수를 이용해 개인화된 예측 평점 구하기

In [9]:
ratings_pred = predict_rating(ratings_matrix.values, item_sim_df.values)
ratings_pred_matrix = pd.DataFrame(data=ratings_pred, index=ratings_matrix.index, columns=ratings_matrix.columns)
ratings_pred_matrix.head(3)

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.070345,0.577855,0.321696,0.227055,0.206958,0.194615,0.249883,0.102542,0.157084,0.178197,...,0.113608,0.181738,0.133962,0.128574,0.006179,0.212070,0.192921,0.136024,0.292955,0.720347
2,0.018260,0.042744,0.018861,0.000000,0.000000,0.035995,0.013413,0.002314,0.032213,0.014863,...,0.015640,0.020855,0.020119,0.015745,0.049983,0.014876,0.021616,0.024528,0.017563,0.000000
3,0.011884,0.030279,0.064437,0.003762,0.003749,0.002722,0.014625,0.002085,0.005666,0.006272,...,0.006923,0.011665,0.011800,0.012225,0.000000,0.008194,0.007017,0.009229,0.010420,0.084501

-> 실제 영화 평점이 0이던 것에서 내적 때문에 값이 부여되는 경우가 많이 발생
* 이전에 평점이 부여된 데이터에 대해서만 오차 정도 측정

In [10]:
from sklearn.metrics import mean_squared_error

# 사용자가 평점을 부여한 영화에 대해서만 예측 성능 평가 MSE를 구함.
def get_mse(pred,actual):
  # 평점이 있는 실제 영화만 추출
  pred = pred[actual.nonzero()].flatten()
  actual = actual[actual.nonzero()].flatten()
  return mean_squared_error(pred,actual)

print('아이템 기반 모든 최근접 이웃 MSE: ', get_mse(ratings_pred,ratings_matrix.values))

아이템 기반 모든 최근접 이웃 MSE:  9.895354759094706

-> mse 값을 줄이는 방향으로 업데이트하기
* 가장 비슷한 유사도를 가지는 영화에 대해서만 유사도 벡터 적용 (n값을 부여함)

In [11]:
def predict_rating_topsim(ratings_arr, item_sim_arr,n=20):
  # 사용자-아이템 평점 행렬 크기만큼 0으로 채운 예측 행렬 초기화
  pred = np.zeros(ratings_arr.shape)
  # 사용자-아이템 평점 행렬의 열 크기만큼 루프 수행.
  for col in range(ratings_arr.shape[1]):
    # 유사도 행렬에서 유사도가 큰 순으로 n개 데이터 행렬의 인덱스 반환
    top_n_items = [np.argsort(item_sim_arr[:,col])[:-n-1:-1]]
    # 개인화 된 예측 평점을 계산
    for row in range(ratings_arr.shape[0]):
      pred[row,col] = item_sim_arr[col,:][top_n_items].dot(ratings_arr[row,:][top_n_items].T)
      pred[row,col] /= np.sum(np.abs(item_sim_arr[col,:][top_n_items]))
  return pred

In [12]:
# 예측 평점과 실제 평점 간 MSE 구하기
ratings_pred = predict_rating_topsim(ratings_matrix.values, item_sim_df.values,n=20)
print('아이템 기반 최근접 TOP-20 이웃 MSE: ', get_mse(ratings_pred,ratings_matrix.values))

# 계산된 예측 평점 데이터는 DataFrame으로 재생성
ratings_pred_matrix = pd.DataFrame(data=ratings_pred, index=ratings_matrix.index, columns=ratings_matrix.columns)

아이템 기반 최근접 TOP-20 이웃 MSE:  3.6949827608772314

In [13]:
# 특정 사용자에 대한 영화 추천
user_rating_id = ratings_matrix.loc[9,:]
user_rating_id[user_rating_id>0].sort_values(ascending=False)[:10]

title
Adaptation (2002)                                                                 5.0
Citizen Kane (1941)                                                               5.0
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    5.0
Producers, The (1968)                                                             5.0
Lord of the Rings: The Two Towers, The (2002)                                     5.0
Lord of the Rings: The Fellowship of the Ring, The (2001)                         5.0
Back to the Future (1985)                                                         5.0
Austin Powers in Goldmember (2002)                                                5.0
Minority Report (2002)                                                            4.0
Witness (1985)                                                                    4.0
Name: 9, dtype: float64

-> 대작 영화나 어드벤처 영화, 코미드 영화 등 흥생성이 좋은 영화에 높은 평점 부여

In [4]:
# 특정 사용자에게 아이템 기반 협업 필터링을 통해 영화 추천
def get_unseen_movies(ratings_matrix,userId):
  # userId로 입력받은 사용자의 모든 영화 정보를 추출해 Series로 반환함.
  # 반환된 user_rating은 영화명(title)을 인덱스로 가지는 Series 객체임.
  user_rating = ratings_matrix.loc[userId,:]

  # user_rating이 0보다 크면 기존에 관람한 영화임. 대상 인덱스를 추출해 list 객체로 만듦.
  already_seen = user_rating[user_rating>0].index.tolist()

  # 모든 영화명을 list 객체로 만듦.
  movies_list = ratings_matrix.columns.tolist()

  # list comprehension으로 already_seen에 해당하는 영화는 movies_list에서 제외함.
  unseen_list = [movie for movie in movies_list if movie not in already_seen]

  return unseen_list

* 사용자가 영화의 평점을 주지 않은 추천 대상 영화 정보와 predict_rating_topsim()에서 추출한 사용자별 아이템 유사도에 기반한 예측 평점 데이터 세트를 이용해 최종 영화 추천 함수 생성

In [ ]:
def recomm_movie_by_userid(pred_df, userId, unseen_list, top_n=10):
  # 예측 평점 DataFrame에서 사용자id 인덱스와 unseen_list로 들어온 영화명 칼럼을 추출해
  # 가장 예측 평점이 높은 순으로 정렬함.
  recomm_movies=pred_df.loc[userId, unseen_list].sort_values(ascending=False)[:top_n]
  return recomm_movies

# 사용자가 관람하지 않는 영화명 추출
unseen_list = get_unseen_movies(ratings_matrix,9)

# 아이템 기반의 최근접 이웃 협업 필터링으로 영화 추천
recomm_movies = recomm_movie_by_userid(ratings_pred_matrix,9, unseen_list, top_n=10)

# 평점 데이터를 DataFrame으로 생성.
recomm_movies = pd.DataFrame(data=recomm_movies.values, index=recomm_movies.index,columns=['pred_score'])

recomm_movies

# 07 행렬 분해를 이용한 잠재 요인 협업 필터링 실습

* 행렬 분해를 이용한 잠재 요인 협업 필터링은 sgd나 als 기반 행렬 분해가 주로 이용
* 행렬 분해 로직을 함수로 만들어 확률적 경사 하강법을 이용한 행렬 분해 함수 생성

In [1]:
from sklearn.metrics import mean_squared_error

def get_rmse(R,P,Q,non_zeros):
  error=0
  # 두 개의 분해된 행렬 P와 Q.T의 내적으로 예측 R 행렬 생성
  full_pred_matrix = np.dot(P,Q.T)

  # 실제 R 행렬에서 널이 아닌 값의 위치 인덱스 추출해 실제 R 행렬과 예측 행렬의 RMSE 추출
  x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
  y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
  R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
  full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
  mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
  rmse = np.sqrt(mse)

  return rmse

In [2]:
def matrix_factorization(R,K,steps=200, learning_rate=0.01, r_lambda=0.01):
  num_users, num_items = R.shape
  # P와 Q 매트릭스의 크기를 지정하고 정규 분포를 가진 랜덤한 값으로 입력
  np.random.seed(1)
  P= np.random.normal(scale=1/K, size=(num_users,K))
  Q= np.random.normal(scale=1/K, size=(num_items,K))

  prev_rmse=10000
  break_count=0

  # R>0인 행 위치, 열 위치, 값을 non_zeros 리스트 객체에 저장.
  non_zeros = [(i,j,R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j]>0]

  # SGD기법으로 P와 Q 매트릭스를 계속 업데이트.
  for step in range(steps):
    for i,j,r in non_zeros:
      # 실제 값과 예측 값의 차이인 오류 값 구함
      eij = r - np.dot(P[i,:],Q[j,:].T)
      # Regularization을 반영한 SGD 업데이트 공식 적용
      P[i,:]=P[i,:] + learning_rate*(eij*Q[j,:] - r_lambda*P[i,:])
      Q[j,:]=Q[j,:] + learning_rate*(eij*P[i,:] - r_lambda*Q[j,:])

    rmse = get_rmse(R,P,Q, non_zeros)
    if (step%10)==0:
      print('### iteration step:', step, 'rmse:',rmse)

  return P,Q

In [7]:
# 영화 평점 행렬 데이터를 새롭게 DataFrame으로 로딩한 후 사용자-아이템 평점 행렬로 만들기

import numpy as np
import pandas as pd

movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

ratings= ratings[['userId', 'movieId','rating']]
ratings_matrix = ratings.pivot_table('rating', index='userId', columns='movieId')

# title 칼럼을 얻기 위해 movies와 조인 수행
rating_movies = pd.merge(ratings, movies, on='movieId')

# columns ='title'로 title 칼럼으로 pivot 수행.
ratings_matrix = rating_movies.pivot_table('rating',index='userId',columns='title')

In [8]:
# 사용자-아이템 평점 행렬 행렬 분해 수행
P,Q = matrix_factorization(ratings_matrix.values, K=50, steps=200, learning_rate=0.01, r_lambda=0.01)
pred_matrix = np.dot(P,Q.T)

### iteration step: 0 rmse: 2.9023619751336867
### iteration step: 10 rmse: 0.7335768591017927
### iteration step: 20 rmse: 0.5115539026853442
### iteration step: 30 rmse: 0.37261628282537446
### iteration step: 40 rmse: 0.2960818299181014
### iteration step: 50 rmse: 0.2520353192341642
### iteration step: 60 rmse: 0.22487503275269854
### iteration step: 70 rmse: 0.2068545530233154
### iteration step: 80 rmse: 0.19413418783028685
### iteration step: 90 rmse: 0.18470082002720406
### iteration step: 100 rmse: 0.17742927527209104
### iteration step: 110 rmse: 0.1716522696470749
### iteration step: 120 rmse: 0.16695181946871726
### iteration step: 130 rmse: 0.16305292191997542
### iteration step: 140 rmse: 0.15976691929679646
### iteration step: 150 rmse: 0.1569598699945732
### iteration step: 160 rmse: 0.15453398186715425
### iteration step: 170 rmse: 0.15241618551077643
### iteration step: 180 rmse: 0.1505508073962831
### iteration step: 190 rmse: 0.1488947091323209

In [10]:
# 쉬운 이해를 위해 예측 사용자-아이템 평점 행렬을 영화타이틀 컬럼명으로 변경
ratings_pred_matrix = pd.DataFrame(data=pred_matrix, index=ratings_matrix.index, columns=ratings_matrix.columns)
ratings_pred_matrix.head(3)

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,3.055084,4.092018,3.564130,4.502167,3.981215,1.271694,3.603274,2.333266,5.091749,3.972454,...,1.402608,4.208382,3.705957,2.720514,2.787331,3.475076,3.253458,2.161087,4.010495,0.859474
2,3.170119,3.657992,3.308707,4.166521,4.311890,1.275469,4.237972,1.900366,3.392859,3.647421,...,0.973811,3.528264,3.361532,2.672535,2.404456,4.232789,2.911602,1.634576,4.135735,0.725684
3,2.307073,1.658853,1.443538,2.208859,2.229486,0.780760,1.997043,0.924908,2.970700,2.551446,...,0.520354,1.709494,2.281596,1.782833,1.635173,1.323276,2.887580,1.042618,2.293890,0.396941

* 행렬을 이용해 개인화된 영화 추천

In [6]:
def recomm_movie_by_userid(pred_df, userId, unseen_list, top_n=10):
  # 예측 평점 DataFrame에서 사용자id 인덱스와 unseen_list로 들어온 영화명 칼럼을 추출해
  # 가장 예측 평점이 높은 순으로 정렬함.
  recomm_movies=pred_df.loc[userId, unseen_list].sort_values(ascending=False)[:top_n]
  return recomm_movies

In [11]:
# 사용자가 관람하지 않은 영화명 추출
unseen_list = get_unseen_movies(ratings_matrix,9)

# 잠재 요인 협업 필터링으로 영화 추천
recomm_movies = recomm_movie_by_userid(ratings_pred_matrix,9, unseen_list, top_n=10)

# 평점 데이터를 DataFrame으로 생성.
recomm_movies = pd.DataFrame(data=recomm_movies.values, index=recomm_movies.index, columns=['pred_score'])
recomm_movies

                                                    pred_score
title
Rear Window (1954)                                    5.704612
South Park: Bigger, Longer and Uncut (1999)           5.451100
Rounders (1998)                                       5.298393
Blade Runner (1982)                                   5.244951
Roger & Me (1989)                                     5.191962
Gattaca (1997)                                        5.183179
Ben-Hur (1959)                                        5.130463
Rosencrantz and Guildenstern Are Dead (1990)          5.087375
Big Lebowski, The (1998)                              5.038690
Star Wars: Episode V - The Empire Strikes Back ...    4.989601

# 08 파이썬 추천 시스템 패키지 - Surprise

**Surprise 패키지 소개**
* Surprise는 파이썬 기반에서 사이킷런과 유사한 API와 프레임워크를 제공

In [2]:
pip install scikit-surprise

Collecting scikit-surprise
  Downloading scikit-surprise-1.1.3.tar.gz (771 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 772.0/772.0 kB 7.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: joblib>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise) (1.3.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise) (1.11.3)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (setup.py) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.3-cp310-cp310-linux_x86_64.whl size=3163497 sha256=01f98e244a9014cb5df68d9324687d294a0fd8397fb61e9250abb26e0680be25
  Stored in directory: /root/.cache/pip/wheels/a5/ca/a8/4e28def53797fdc4363ca4af740db15a9c2f1595ebc51fb445
Successfully built scikit-surprise
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.3

* 다양한 추천 알고리즘을 쉽게 적용해 추천 시스템 구축 가능
* 사이킷런의 핵심 api와 유사한 이름을 가지고 있어 편리

**Surprise를 이용한 추천 시스템 구축**

In [3]:
# surprise 관련 모듈 임포트
from surprise import SVD
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import train_test_split

* 추천을 위한 데이터 로딩 - Dataset 클래스 이용
* Movie Lens 데이터 세트의 사용자-영화 평점 데이터 포맷과 같은 주요 데이터가 로우 레벨 형태로 되어 있을 때만 가능
* 사이트에서 제공하는 과거 버전의 데이터 세트를 가져와 로컬 디렉터리에 저장한 뒤 데이터 로딩

In [4]:
data = Dataset.load_builtin('ml-100k')
# 수행 시마다 동일하게 데이터를 분할하기 위해 random_state 값 부여
trainset, testset = train_test_split(data, test_size=.25, random_state=0)

Dataset ml-100k could not be found. Do you want to download it? [Y/n] Y
Trying to download dataset from https://files.grouplens.org/datasets/movielens/ml-100k.zip...
Done! Dataset ml-100k has been saved to /root/.surprise_data/ml-100k

* 원본 데이터 형태 ('로우 레벨의' 사용자-아이템 평점 데이터)를 사용해야 함

In [5]:
# 알고리즘 객체 생성 후 train 데이터 기반 추천 알고리즘 학습
algo=SVD()
algo.fit(trainset)

* test: 사용자-아이템 평점 데이터 세트 전체에 대해서 추천을 예측
* predict: 개별 사용자와 영화에 대한 추천 평점 반환

In [6]:
predictions = algo.test(testset)
print('prediction type:', type(predictions),'size:', len(predictions))
print('prediction 결과의 최초 5개 추출')
predictions[:5]

prediction type: <class 'list'> size: 25000
prediction 결과의 최초 5개 추출

[Prediction(uid='120', iid='282', r_ui=4.0, est=3.722133092216387, details={'was_impossible': False}),
 Prediction(uid='882', iid='291', r_ui=4.0, est=3.561147084156995, details={'was_impossible': False}),
 Prediction(uid='535', iid='507', r_ui=5.0, est=3.865511613194, details={'was_impossible': False}),
 Prediction(uid='697', iid='244', r_ui=5.0, est=3.324112220628146, details={'was_impossible': False}),
 Prediction(uid='751', iid='385', r_ui=4.0, est=3.2684980219532958, details={'was_impossible': False})]

-> 결과는 리스트이고 크기는 입력 인자 데이터 세트 크기와 같은 25000개의 prediction 객체를 내부에 가짐
* uid: 개별 사용자 아이디, iid: 영화 아이디, r_ui: 실제 평점

In [7]:
[(pred.uid, pred.iid, pred.est) for pred in predictions[:3]]

[('120', '282', 3.722133092216387),
 ('882', '291', 3.561147084156995),
 ('535', '507', 3.865511613194)]

In [8]:
# 개별 사용자 아이디, 아이템 아이디 입력을 통해 추천 예측 평점 및 정보 반환

# 사용자 아이디, 아이템 아이디는 문자열로 입력해야 함.
uid = str(196)
iid = str(302)
pred = algo.predict(uid,iid)
print(pred)

user: 196        item: 302        r_ui = None   est = 4.26   {'was_impossible': False}

-> test 메서드는 입력 데이터 세트의 모든 사용자와 아이템 아이디에 대해서 predict 반복 수행한 것(est=예측 평점)

In [9]:
# 예측 평점과 실제 평점의 차이 평가
accuracy.rmse(predictions)

RMSE: 0.9472

0.9472468427559603

**Surprise 주요 모듈 소개**
* dataset: user_id, item_id, rating 데이터가 로우 레벨로 된 데이터 세트만 적용 가능 (그 이후 데이터들은 로딩 불가)

**os 파일 데이터를 Surprise 데이터 세트로 로딩**
* Dataset.load_from_file API를 이용해 지정된 디렉터리에 있는 사용자-아이템 평점 데이터 로딩
* 단, 헤더 문자열이 있어서는 안 됨

In [11]:
import pandas as pd

ratings = pd.read_csv('ratings.csv')

# ratings_noh.csv 파일로 업로드 시 인덱스와 헤더를 모두 제거한 새로운 파일 생성.
ratings.to_csv('ratings_noh.csv', index=False, header=False)

* 헤더가 삭제된 파일을 load_from_file()을 이용해 dataset로 로드
* 데이터 파일의 파싱 포맷 정의가 필요함 -> 칼럼명, 칼럼 분리문자, 최소~최대 평점을 입력해 객체 생성

In [13]:
from surprise import Reader

reader = Reader(line_format='user item rating timestamp', sep=',', rating_scale=(0.5,5))
data=Dataset.load_from_file('ratings_noh.csv',reader=reader)

In [14]:
# SVD 행렬 분해 기법을 이용해 추천 예측
trainset,testset = train_test_split(data,test_size=.25, random_state=0)

# 수행 시마다 동일한 결과를 도출하기 위해 random_state 설정
algo = SVD(n_factors=50, random_state=0)

# 학습 데이터 세트로 학습하고 나서 테스트 데이터 세트로 평점 예측 후 RMSE 평가
algo.fit(trainset)
predictions = algo.test(testset)
accuracy.rmse(predictions)

RMSE: 0.8682

0.8681952927143516

**판다스 DataFrame에서 Surprise 데이터 세트로 로딩**
* 판다스에서 surprise 데이터 세트로 로딩하는 방법: load_from_df() 사용

In [15]:
import pandas as pd
from surprise import Reader, Dataset

ratings = pd.read_csv('ratings.csv')
reader= Reader(rating_scale=(0.5,5.0))

# ratings DataFrame에서 칼럼은 사용자 아이디, 아이템 아이디, 평점 순서를 지켜야 합니다.
data = Dataset.load_from_df(ratings[['userId','movieId','rating']],reader)

trainset,testset = train_test_split(data,test_size=.25, random_state=0)
algo = SVD(n_factors=50, random_state=0)
algo.fit(trainset)
predictions = algo.test(testset)
accuracy.rmse(predictions)

RMSE: 0.8682

0.8681952927143516

**Surprise 추천 알고리즘 클래스**
* SVD, KNNBasic, BaselineOnly 등
* SVD++가 성능이 가장 좋지만 상대적으로 시간이 너무 오래 걸려 데이터가 조금만 커도 사용하기가 어려울 것으로 보임 -> SVD++ 제외, SVD & k-NN Baseline이 가장 성능 평가 수치가 좋음

**베이스라인 평점**
* 어떤 활동을 평가할 때 사람에 따라 평가 기준이 다양함 -> 한 개인의 성향을 반영해 아이템 평가에 편향성 요소를 반영하여 평점을 부과 = 베이스라인 평점
* 베이스라인 평점 = 전체 평균 평점 + 사용자 편향 점수 (사용자별 아이템 평점 평균 값 - 전체 평균 평점) + 아이템 편향 점수 (아이템별 평점 평균 값 - 전체 평균 평점)

**교차 검증과 하이퍼 파라미터 튜닝**
* Surprise는 사이킷런과 유사한 cross_validate()와 GridSearchCV 제공
* cross_validate()를 이용해 ratings.csv를 DataFrame으로 로딩한 데이터를 5개의 학습/검증 폴드 데이터 세트로 분리해 교차 검증을 수행, RMSE,MAE로 성능 평가

In [16]:
from surprise.model_selection import cross_validate

# 판다스 DataFrame에서 Surprise 데이터 세트로 데이터 로딩
ratings = pd.read_csv('ratings.csv')
reader= Reader(rating_scale=(0.5,5.0))
data= Dataset.load_from_df(ratings[['userId', 'movieId','rating']],reader)
algo = SVD(random_state=0)
cross_validate(algo, data, measures=['RMSE','MAE'],cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    0.8766  0.8604  0.8784  0.8823  0.8767  0.8749  0.0075
MAE (testset)     0.6717  0.6618  0.6755  0.6766  0.6745  0.6720  0.0053
Fit time          1.61    1.76    1.74    1.69    2.85    1.93    0.46
Test time         0.42    0.14    0.13    0.22    0.23    0.23    0.10

{'test_rmse': array([0.87660798, 0.86041486, 0.87844376, 0.88226523, 0.87674241]),
 'test_mae': array([0.67165692, 0.66184456, 0.6754979 , 0.67658846, 0.67453294]),
 'fit_time': (1.610407829284668,
  1.7602043151855469,
  1.7425734996795654,
  1.6868374347686768,
  2.854123115539551),
 'test_time': (0.41777634620666504,
  0.13707995414733887,
  0.12707877159118652,
  0.2178516387939453,
  0.2328348159790039)}

-> 폴드 별 성능 평가 수치와 전체 폴드의 평균 성능 평가 수치를 함께 보여줌
* Surprise의 GridSearchCV도 사이킷런과 유사하게 교차 검증을 통한 하이퍼 파라미터 최적화 수행
* n_epochs: 점진적 하강 방식의 반복 횟수 지정, n_factors: svd 잠재 요인 k의 크기 지정

In [17]:
from surprise.model_selection import GridSearchCV

# 최적화 할 파라미터를 딕셔너리 형태로 지정.
param_grid = {'n_epochs': [20,40,60], 'n_factors': [50,100,200]}

# cv를 3개 폴드 세트로 지정, 성능 평가는 rmse, mse로 수행하도록 GridSearchCV 구성
gs = GridSearchCV(SVD, param_grid, measures=['rmse','mae'], cv=3)
gs.fit(data)

# 최고 RMSE Evaluation 점수와 그 때의 하이퍼 파라미터
print(gs.best_score['rmse'])
print(gs.best_params['rmse'])

0.8763493550583888
{'n_epochs': 20, 'n_factors': 50}

**Surprise를 이용한 개인화 영화 추천 시스템 구축**
* Surprise 패키지로 학습된 추천 알고리즘을 기반으로 특정 사용자가 아직 평점을 매기지 않은 영화 중에서 개인 취향에 가장 적절한 영화 추천
* 학습 데이터와 테스 데이터로 분리하지 않고 전체를 학습 데이터로 사용할거지만 train_test_split()을 이용해 내부의 클래스 객체로 변환하지 않으면 오류 발생

In [ ]:
# 다음 코드는 train_test_split()으로 분리되지 않는 데이터 세트에 fit()을 호출해 오류가 발생합니다.
data = Dataset.load_from_df(ratings[['userId', 'movieId','rating']],reader)
algo = SVD(n_factors=50, random_state=0)
algo.fit(data)

* 데이터 세트 전체를 학습데이터로 사용하려면 DatasetAutoFolds 클래스 이용

In [19]:
from surprise.dataset import DatasetAutoFolds

reader = Reader(line_format='user item rating timestamp', sep=',', rating_scale=(0.5,5))

# DatasetAutoFolds 클래스를 ratings_noh.csv 파일 기반으로 생성.
data_folds = DatasetAutoFolds(ratings_file ='ratings_noh.csv', reader=reader)

# 전체 데이터를 학습 데이터로 생성함.
trainset = data_folds.build_full_trainset()

In [20]:
# SVD 학습
algo = SVD(n_epochs=20, n_factors=50, random_state=0)
algo.fit(trainset)

* userId = 9인 사용자 기준, 아직 평점을 매기지 않은 영화를 movieId 42로 선정한 뒤 예측 평점 계산

In [21]:
# 영화에 대한 상세 속성 정보 DataFrame 로딩
movies = pd.read_csv('movies.csv')

# userId=9의 movieId 데이터를 추출해 movieId=42 데이터가 있는지 확인.
movieIds = ratings[ratings['userId']==9]['movieId']

if movieIds[movieIds==42].count()==0:
  print('사용자 아이디 9는 영화 아이디 42의 평점 없음')
print(movies[movies['movieId']==42])

사용자 아이디 9는 영화 아이디 42의 평점 없음
    movieId                   title              genres
38       42  Dead Presidents (1995)  Action|Crime|Drama

In [22]:
uid = str(9)
iid = str(42)
pred = algo.predict(uid, iid, verbose=True)

user: 9          item: 42         r_ui = None   est = 3.13   {'was_impossible': False}

-> 추천 예측 평점 = 3.13
* 평점을 매기지 않은 전체 영화 추출 후 예측 평점 순으로 영화 추천

In [ ]:
def get_unseen_surprise(ratings,movies,userId):
  # 입력값으로 들어온 userId에 해당하는 사용자가 평점을 매긴 모든 영화를 리스트로 생성
  seen_movies = ratings[ratings['userId']==userId]['movieId'].tolist()

  # 모든 영화의 movieId를 리스트로 생성.
  total_movies = movies['movieId'].tolist()
  # 모든 영화의 movieId 중 이미 평점을 매긴 영화의 movieId를 제외한 후 리스트로 생성
  unseen_movies = [movie for movie in total_movies if movie not in seen_movies]
  print('평점 매긴 영화 수:', len(seen_movies), '추천 대상 영화 수:', len(unseen_movies), '전체 영화 수:', len(total_movies))
  return unseen_movies
unseen_movies = get_unseen_surprise(ratings, movies, 9)

* SVD를 이용해 높은 예측 평점을 가진 순으로 영화 추천

In [24]:
def recomm_movie_by_surprise(algo, userId, unseen_movies, top_n=10):
  # 알고리즘 객체의 predict() 메서드를 평점이 없는 영화에 반복 수행한 후 결과를 list 객체로 저장
  predictions = [algo.predict(str(userId),str(movieId)) for movieId in unseen_movies]

  # predictions list 객체는 surprise의 Predictions 객체를 원소로 가지고 있음.
  # [Predictions(uid='9', iid='1', est=3.69), Prediction(uid='9',iid='2',est=2.98)...]

  # 이를 est 값으로 정렬하기 위해서 아래의 sortkey_est 함수를 정의함.
  # sortkey_est 함수는 list 객체의 sort() 함수의 키 값으로 사용되어 정렬 수행.
  def sortkey_est(pred):
    return pred.est

  # sortkey_est() 반환 값의 내림 차순으로 정렬 수행하고 top_n개의 최상위 값 추출.
  predictions.sort(key=sortkey_est, reverse=True)
  top_predictions = predictions[:top_n]

  # top_n으로 추출된 영화의 정보 추출. 영화 아이디, 추천 예상 평점, 제목 추출
  top_movie_ids = [int(pred.iid) for pred in top_predictions]
  top_movie_rating = [pred.est for pred in top_predictions]
  top_movie_titles = movies[movies.movieId.isin(top_movie_ids)]['title']

  top_movie_preds = [(id,title,rating) for id, title, rating in \
                     zip(top_movie_ids, top_movie_titles, top_movie_rating)]
  return top_movie_preds

In [25]:
unseen_movies = get_unseen_surprise(ratings, movies,9)
top_movie_preds = recomm_movie_by_surprise(algo,9,unseen_movies, top_n=10)

print('##### Top-10 추천 영화 리스트 #####')
for top_movie in top_movie_preds:
  print(top_movie[1],':', top_movie[2])

평점 매긴 영화 수: 46 추천 대상 영화 수: 9696 전체 영화 수: 9742
##### Top-10 추천 영화 리스트 #####
Usual Suspects, The (1995) : 4.306302135700814
Star Wars: Episode IV - A New Hope (1977) : 4.281663842987387
Pulp Fiction (1994) : 4.278152632122759
Silence of the Lambs, The (1991) : 4.226073566460876
Godfather, The (1972) : 4.1918097904381995
Streetcar Named Desire, A (1951) : 4.154746591122657
Star Wars: Episode V - The Empire Strikes Back (1980) : 4.122016128534504
Star Wars: Episode VI - Return of the Jedi (1983) : 4.108009609093436
Goodfellas (1990) : 4.083464936588478
Glory (1989) : 4.07887165526957